# fly.toml app configuration file generated for wetube-yukddong on 2023-04-29T00:08:47+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wetube-yukddong"
primary_region = "nrt"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
