# fly.toml app configuration file generated for wetube-yukdong on 2023-04-29T01:24:25+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wetube-yukdong"
primary_region = "nrt"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
